#!/bin/bash
clear

###############################
#
# Parametros:
#  - Lista de Usuarios a crear
#  - Usuario del cual se obtendra la clave
#
#  Tareas:
#  - Crear los usuarios segun la lista recibida en los grupos descriptos
#  - Los usuarios deberan de tener la misma clave que la del usuario pasado por parametro
#
###############################

LISTA=$1 alta_usuarios

ANT_IFS=$IFS
IFS=$'\n'
for LINEA in `cat $LISTA |  grep -v ^#`
do
G_R1_MAURO_LAIME
G_R2_ADRIAN_FERRERA
G_R3_MAURO_LAIME
G_R4_GOMEZ_EMILSE
G_R5_CARLA_LOPEZ
G_R6_NICOLAS_MARGNI
	USUARIO=$(echo  $LINEA |awk -F ':' '{print $1}')
	GRUPO=$(echo  $LINEA |awk -F ':' '{print $2}')
	echo "sudo useradd -m -s /bin/bash -g $GRUPO_5 $USUARIO"
done
IFS=$ANT_IFS
