---
- hosts: 
   - all
  #- testing
  #- desarrollo
  #- produccion

    - name: "Import role 01"
      import_role:
        name: role_1mauro
      tags:
        - mauro
    
    - name: "Import role 02"
      import_role:
        name: role_2adrian
      tags:
        - adrian

    - name: "Import role 03"
      import_role:
        name: role_3maurob
      tags:
        - mauro
    
    - name: "Import role 04"
      import_role:
        name: role_4emilse
      tags:
        - emilse
    
    - name: "Import role 05"
      import_role:
        name: role_5carla
      tags:
        - carla
    
    - name: "Import role 06"
      import_role:
        name: role_6nicolas
      tags:
        - nicolas
    

